---
###############################################################################
# Remove a defined systemd mount
###############################################################################
#
# Args:
#   systemd: dict containing one element from systemd_mounts.

- name: 'Systemd | unload | mount {{ systemd.name }}'
  when: systemd.state | lower == 'absent' and not systemd.drop_in
  notify: 'Handlers | reload systemd'
  ansible.builtin.file:
    dest: '{{ systemd_role_root }}/{{ systemd.name }}.mount'
    state: 'absent'

- name: 'Systemd | unload | drop-in | mount {{ systemd.name }}'
  when: systemd.state | lower == 'absent' and systemd.drop_in
  notify: 'Handlers | reload systemd'
  ansible.builtin.file:
    dest: '{{ systemd_role_root }}/{{ systemd.name }}.mount.d'
    state: 'absent'
