---
###############################################################################
# Remove a defined systemd timer
###############################################################################
#
# Args:
#   systemd: dict containing one element from systemd_timers.

- name: 'Systemd | unload | timer {{ systemd.name }}'
  ansible.builtin.file:
    dest: '{{ systemd_role_root }}/{{ systemd.name }}.timer'
    state: 'absent'
  when: systemd.state | lower == 'absent'
  notify: 'Handlers | reload systemd'
