---
###############################################################################
# Remove a defined systemd timer
###############################################################################
#
# Args:
#   systemd: dict containing one element from systemd_timers.

- name: 'Systemd | unload | timer {{ systemd.name }}'
  when: systemd.state | lower == 'absent' and not systemd.drop_in
  notify: 'Handlers | reload systemd'
  ansible.builtin.file:
    dest: '{{ systemd_role_root }}/{{ systemd.name }}.timer'
    state: 'absent'

- name: 'Systemd | unload | drop-in | timer {{ systemd.name }}'
  when: systemd.state | lower == 'absent' and systemd.drop_in
  notify: 'Handlers | reload systemd'
  ansible.builtin.file:
    dest: '{{ systemd_role_root }}/{{ systemd.name }}.timer.d'
    state: 'absent'
