---
- name: 'Prepare'
  hosts: 'all'
  gather_facts: false
  become: true
  tasks:
    - name: 'Prepare | add nfs-kernel-server'
      ansible.builtin.apt:
        name: 'nfs-kernel-server'  # Does not support reloading, only restart.
        update_cache: true
        state: 'present'
