---
###############################################################################
# Disable a defined systemd mount
###############################################################################
#
# Args:
#   systemd: dict containing one element from systemd_mounts.

- name: 'Systemd | disable | mount {{ systemd.name }}'
  when: >
    systemd.state | lower == 'absent' and
    (systemd_daemon_reload_enable | default(true))
  notify: 'Handlers | reload systemd'
  ansible.builtin.service:
    name: '{{ systemd.name }}.mount'
    enabled: false
    state: 'stopped'
  failed_when: false  # non-existing mounts can still be marked absent
