---
###############################################################################
# Disable a defined systemd service
###############################################################################
#
# Args:
#   systemd: dict containing one element from systemd_services.

- name: 'Systemd | disable | service {{ systemd.name }}'
  when: >
    systemd.state | lower == 'absent' and
    not (systemd_testing_enable | default(false))
  notify: 'Handlers | reload systemd'
  ansible.builtin.service:
    name: '{{ systemd.name }}.service'
    enabled: false
    state: 'stopped'
