---
###############################################################################
# Disable a defined systemd timer
###############################################################################
#
# Args:
#   systemd: dict containing one element from systemd_timers.

- name: 'Systemd | disable | timer {{ systemd.name }}'
  when: >
    systemd.state | lower == 'absent' and
    (systemd_daemon_reload_enable | default(true))
  notify: 'Handlers | reload systemd'
  ansible.builtin.service:
    name: '{{ systemd.name }}.timer'
    enabled: false
    state: 'stopped'
  failed_when: false  # non-existing timers can still be marked absent.
