---
###############################################################################
# Enable a defined systemd mount
###############################################################################
#
# Args:
#   systemd: dict containing one element from systemd_mounts.

- name: 'Systemd | enable | mount {{ systemd.name }}'
  when: >
    systemd.state | lower == 'present' and
    (systemd_daemon_reload_enable | default(true))
  notify: 'Handlers | reload systemd'
  block:
    # Reload or restart is not supported; check results and start manually.
    - name: 'Systemd | enable | reload {{ systemd.name }}'
      ansible.builtin.service:
        name: '{{ systemd.name }}.mount'
        enabled: true
