---
###############################################################################
# Enable a defined systemd timer
###############################################################################
#
# Args:
#   systemd: dict containing one element from systemd_timers.

- name: 'Systemd | enable | timer {{ systemd.name }}'
  when: >
    systemd.state | lower == 'present' and
    (systemd_daemon_reload_enable | default(true))
  notify: 'Handlers | reload systemd'
  ansible.builtin.service:
    name: '{{ systemd.name }}.timer'
    enabled: true
    state: 'restarted'
