---
###############################################################################
# Enable a defined systemd timer
###############################################################################
#
# Args:
#   systemd: dict containing one element from systemd_timers.

- name: 'Systemd | enable | timer {{ systemd.name }}'
  ansible.builtin.service:
    name: '{{ systemd.name }}.timer'
    enabled: true
    state: 'restarted'
  when: systemd.state | lower == 'present' and not systemd_testing_enable
  notify: 'Handlers | reload systemd'
