---
###############################################################################
# Configure Systemd unit services.
###############################################################################
# Creates, enables, and reloads a defined systemd service/timer.
#
# Args:
#   systemd: dict containing one element from systemd_services.

- name: 'Systemd | service | manage {{ systemd.name }}'
  when: systemd.state | lower == 'present'
  notify: 'Handlers | reload systemd'
  block:
    - name: 'Systemd | service | add {{ systemd.name }}'
      ansible.builtin.template:
        src: 'service.j2'
        dest: '{{ systemd_role_root }}/{{ systemd.name }}.service'
        owner: 'root'
        group: 'root'
        mode: '0644'

    - name: 'Systemd | service | enable'
      ansible.builtin.service:
        name: '{{ systemd.name }}.service'
        enabled: true
        state: 'reloaded'
      when: not systemd_testing_enable
