---
###############################################################################
# Configure Systemd unit services.
###############################################################################
# Removes specified service.
#
# Args:
#   systemd: dict containing one element from systemd_services.

- name: 'Systemd | service | remove {{ systemd.name }}'
  when: systemd.state | lower == 'absent'
  notify: 'Handlers | reload systemd'
  block:
    - name: 'Systemd | service | disable'
      ansible.builtin.service:
        name: '{{ systemd.name }}.service'
        enabled: false
        state: 'stopped'
      when: not systemd_testing_enable

    - name: 'Systemd | service | remove {{ systemd.name }}'
      ansible.builtin.file:
        dest: '{{ systemd_role_root }}/{{ systemd.name }}.service'
        state: 'absent'
