---
###############################################################################
# Systemd Handlers
###############################################################################

- name: 'Handlers | reload systemd'
  when: not (systemd_testing_enable | default(false))
  ansible.builtin.systemd_service:
    daemon_reload: true
