---
###############################################################################
# Mount Automount
###############################################################################
# Filesystem mount operations require VM.
#
# Tests:
# * Create a mount, mount override, automount, automount override.

dependency:
  name: 'galaxy'
driver:
  name: 'vagrant'
  provider:
    name: 'virtualbox'
    config_options:
      ssh.keep_alive: true
      ssh.remote_user: 'root'
    options:
      append_platform_to_hostname: false
provisioner:
  name: 'ansible'
  config_options:
    defaults:
      interpreter_python: 'auto_silent'
      callback_whitelist: 'profile_tasks, timer, yaml'
  inventory:
    group_vars:
      all:
        systemd_mounts:
          - name: 'mnt-test'
            state: 'present'
            drop_in: false
            unit:
              description: 'test mount tmpfs'
            mount:
              what: 'tmpfs'
              where: '/mnt/test'
              type: 'tmpfs'
              options:
                - 'noatime'
                - 'nosuid'
                - 'nodev'
                - 'noexec'
                - 'mode=1777'
            install:
              wanted_by:
                - 'multi-user.target'
          - name: 'mnt-test'
            state: 'present'
            drop_in: true
            unit:
              description: 'override configuration test'
        systemd_automounts:
          - name: 'mnt-test'
            state: 'present'
            drop_in: false
            unit:
              description: 'automount configuration test'
            automount:
              where: '/mnt/test'
            install:
              wanted_by:
                - 'multi-user.target'
          - name: 'mnt-test'
            state: 'present'
            drop_in: true
            unit:
              description: 'override automount configuration test'
platforms:
  - name: 'systemd-mount-automount'
    box: 'inception-of-things/debian-trixie'
    memory: 4096
    cpus: 2
    interfaces:
      - network_name: private_network  # network_name required
        auto_config: true
        type: 'dhcp'
verifier:
  name: 'ansible'
lint: |
  set -e
  yamllint .
  ansible-lint .
scenario:
  test_sequence:
    # - 'dependency'
    # - 'cleanup'
    - 'destroy'
    - 'syntax'
    - 'create'
    # - 'prepare'
    - 'converge'
    # - 'idempotence'  # drop-ins always created
    # - 'side_effect'
    - 'verify'
    # - 'cleanup'
    - 'destroy'
