---
- name: 'Verify'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Verify | assert fact_caching not expired'
      ansible.builtin.assert:
        quiet: true
        that:
          - '_test_systemd_cache_default_stat is defined'
        fail_msg: '⚠ fact_caching has expired; re-run prepare.'

    - name: 'Verify | snapsnot systemd directory'
      ansible.builtin.stat:
        path: '/etc/systemd/system'
      register: _test_systemd_default_stat

    - name: 'Verify | assert systemd directory same'
      ansible.builtin.assert:
        quiet: true
        that:
          - _test_systemd_default_stat.stat == _test_systemd_cache_default_stat.stat  # yamllint disable-line rule:line-length
        fail_msg: >
          '✘ /etc/systemd/system directory modified during role execution.'
