---
- name: 'Default | verify'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Default | verify | snapsnot systemd directory'
      ansible.builtin.stat:
        path: '/etc/systemd/system'
      register: _test_systemd_default_stat

    - name: 'Default | verify | assert systemd directory same'
      ansible.builtin.assert:
        that:
          - _test_systemd_default_stat == _test_systemd_cache_default_stat
        fail_msg: >
          '/etc/systemd/system directory modified during role execution.'
