---
- name: 'Timer service | converge'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Timer service | converge | create'
      ansible.builtin.include_role:
        name: 'r_pufky.srv.systemd'

- name: 'Timer service | converge | remove'
  hosts: 'systemd-debian-12-timer_service-remove'
  gather_facts: false
  tasks:
    - name: 'Timer service | converge | remove'
      ansible.builtin.include_role:
        name: 'r_pufky.srv.systemd'
  vars:
    systemd_services:
      - name: 'test'
        state: 'present'
        override: false
        unit:
          description: 'test timer service'
          requires: ['test.timer']
        service:
          type: 'simple'
          exec_start: ['echo "this is a test service"']
        exec:
          user: 'root'
          group: 'root'
      - name: 'test'
        state: 'absent'
        override: false
    systemd_timers:
      - name: 'test'
        state: 'present'
        override: false
        unit:
          description: 'test timer'
        timer:
          unit: 'test.service'
          on_boot_sec: '1year'
        install:
          wanted_by: ['timers.target']
      - name: 'test'
        state: 'absent'
        override: false
