---
- name: 'Converge'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Converge | apply r_pufky.deb.systemd'
      ansible.builtin.include_role:
        name: 'r_pufky.deb.systemd'

- name: 'Converge | drop-in'
  hosts: 'systemd-debian-13-file_format_all_options-drop-in'
  gather_facts: false
  tasks:
    - name: >
        Coverge | drop-in |
        apply r_pufky.deb.systemd
      ansible.builtin.include_role:
        name: 'r_pufky.deb.systemd'
      vars:
        systemd_services:
          - name: 'reboot'
            state: 'present'
            drop_in: true
            service:
              exec_start:
                - ''
                - 'echo old exec_start over-written'
        systemd_timers:
          - name: 'reboot'
            state: 'present'
            drop_in: true
            timer:
              on_calendar:
                - ''
                - '1day'
