---
- name: 'File format all options | converge'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'File format all options | converge | apply r_pufky.srv.systemd'
      ansible.builtin.include_role:
        name: 'r_pufky.srv.systemd'
