---
- name: 'File format all options | verify'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'File format all options | verify | unit'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'copy.yml'
      vars:
        test_name: 'File format all options | verify | unit | {{ item }}'
        test_src: 'files/{{ item }}'
        test_file: '/etc/systemd/system/{{ item }}'
        test_owner: 'root'
        test_group: 'root'
        test_mode: '0644'
      loop:
        - 'reboot.service'
        - 'reboot.timer'

- name: 'File format all options | verify'
  hosts: 'systemd-debian-12-file_format_all_options-drop-in'
  gather_facts: false
  tasks:
    - name: 'File format all options | verify | drop-in'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'copy.yml'
      vars:
        test_name: 'File format all options | verify | drop-in | {{ item }}'
        test_src: 'files/{{ item }}.override'
        test_file: '/etc/systemd/system/{{ item }}.d/override.conf'
        test_owner: 'root'
        test_group: 'root'
        test_mode: '0644'
      loop:
        - 'reboot.service'
        - 'reboot.timer'
