---
###############################################################################
# Create a defined systemd mount
###############################################################################
#
# Args:
#   systemd: dict containing one element from systemd_mounts.

- name: 'Systemd | load | mount {{ systemd.name }}'
  when: systemd.state | lower == 'present' and not systemd.drop_in
  notify: 'Handlers | reload systemd'
  ansible.builtin.template:
    src: 'mount.j2'
    dest: '{{ systemd_role_root }}/{{ systemd.name }}.mount'
    owner: 'root'
    group: 'root'
    mode: '0644'

- name: 'Systemd | load | drop-in'
  when: systemd.state | lower == 'present' and systemd.drop_in
  block:
    - name: >
        Systemd | load | drop-in |
        create {{ systemd_role_root }}/{{ systemd.name }}.mount.d
      ansible.builtin.file:  # noqa name[template] directory structure
        path: '{{ systemd_role_root }}/{{ systemd.name }}.mount.d'
        owner: 'root'
        group: 'root'
        mode: '0755'
        recurse: true
        state: 'directory'

    - name: 'Systemd | load | drop-in | mount {{ systemd.name }}'
      notify: 'Handlers | reload systemd'
      ansible.builtin.template:
        src: 'mount.j2'
        dest: '{{
            systemd_role_root ~ "/" ~
            systemd.name ~ ".mount.d/override.conf"
          }}'
        owner: 'root'
        group: 'root'
        mode: '0644'
