---
# Setting non-existent units absent should execute without failures.
dependency:
  name: 'galaxy'
driver:
  name: 'podman'
provisioner:
  name: 'ansible'
  config_options:
    defaults:
      interpreter_python: 'auto_silent'
      callback_whitelist: 'profile_tasks, timer, yaml'
    ssh_connection:
      pipelining: false
  inventory:
    group_vars:
      all:
        systemd_services:
          - name: 'test'
            state: 'absent'
            override: false
        systemd_timers:
          - name: 'test'
            state: 'absent'
            override: false
        systemd_mounts:
          - name: 'mnt-test'
            state: 'absent'
            override: false
        systemd_automounts:
          - name: 'mnt-test'
            state: 'absent'
            override: false
platforms:
  - name: 'systemd-debian-12-absent_nonexistent'
    image: 'ghcr.io/hifis-net/debian-systemd:12'
    systemd: 'always'
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    command: '/lib/systemd/systemd'
    pre_build_image: true
verifier:
  name: 'ansible'
lint: |
  set -e
  yamllint .
  ansible-lint .
scenario:
  test_sequence:
    # - 'dependency'
    # - 'cleanup'
    - 'destroy'
    - 'syntax'
    - 'create'
    # - 'prepare'
    - 'converge'
    - 'idempotence'  # Service created only once.
    # - 'side_effect'
    - 'verify'
    # - 'cleanup'
    - 'destroy'
