---
- name: 'Restart instead of reload | converge'
  hosts: 'all'
  gather_facts: false
  become: true
  tasks:
    - name: 'Restart instead of reload | converge | apply r_pufky.deb.systemd'
      ansible.builtin.include_role:
        name: 'r_pufky.deb.systemd'
