---
- name: 'Verify | nfs-server reloaded'
  hosts: 'all'
  gather_facts: false
  become: true
  tasks:
    - name: 'Verify | query services'
      ansible.builtin.service_facts:

    - name: 'Verify | assert nfs mountd started'
      ansible.builtin.assert:
        quiet: true
        that:
          - ansible_facts.services["nfs-mountd.service"].state == 'running'
        fail_msg: |
          ✘ nfs-server.service should have been started, not reloaded.

          {{ ansible_facts.services["nfs-mountd.service"] }}
